#pragma config(Sensor, S1,     left_light,     sensorEV3_Color)
#pragma config(Sensor, S2,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     back_light,     sensorLightActive)
#pragma config(Sensor, S4,     right_light,    sensorEV3_Color)
#pragma config(Motor,  motorA,          motor_A,       tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          motor_B,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor_C,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          motor_D,       tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void beep(int i);
void check_font_block(float sensor);
void forward(float x);
void backward(float y);
void turn_left();
void two_turn_left();
void turn_right();
void _open();;
void _close();
void _handle();
void close_handle();
void stop_motor();
int check_block_color();
int _handle_status , have_font_block , open_status = 0;


task main()
{
	int counter = 0;

	while(1){
		//if(SensorValue[S1] < 10 && SensorValue[S4] < 10) beep(0);
		int g = 0;
		if(counter >= 2000){

			stop_motor();
			g = check_block_color();
			displayVariableValues(0,g);
			two_turn_left();
			if(SensorValue[S3] < 20) beep(2);
			else beep(1);
			for(int i = 0 ; i < 2000 ; i++){
				forward(0.8);
			}
			stop_motor();
			_open();
			backward(0.5);
			stop_motor();
			_handle();
		}
		if(SensorValue[S2] < 10){
			counter++;
			//stop_motor();
		}
		else{
			forward(0.3);
			counter = 0;
		}
	}

}
int check_block_color(){
	int color,last_ultra,ultra,error;
	last_ultra = SensorValue[S2];
	ultra = SensorValue[S2];
	for(int i = 0; i < 10000 ; i++){
		ultra = SensorValue[S2];
		error = 3 - SensorValue[S2];
		setMotorSpeed(motorA, error*(-3));
		setMotorSpeed(motorD, error*(-3));
	}
	if(SensorValue[S3] > 25){
		color = 6; // orange
	}else{
		color = 9; // black
	}

	for(int i = 0; i < 10000 ; i++){
		ultra = SensorValue[S2];
		error = last_ultra - SensorValue[S2];
		setMotorSpeed(motorA, error*(-3));
		setMotorSpeed(motorD, error*(-3));
	}
	stop_motor();
	return color;

}

void stop_motor(){

	setMotorSpeed(motorA, 0);
	setMotorSpeed(motorD, 0);
}

void _open(){
	for(int n = 0 ; n < 100000 ; n++){
		setMotorSpeed(motorB, 30);
	}
	open_status = 1;
}

void _close(){
	for(int n = 0 ; n < 100000 ; n++){
		setMotorSpeed(motorB, -30);
	}
	open_status = 0;
}

void _handle(){
	if(open_status){

			setMotorSpeed(motorB, -30);
			sleep(8000);
			setMotorSpeed(motorB, 0);
	}
	_handle_status = 1;
}

void _handle(){
	if(_handle_status){

			setMotorSpeed(motorB, 30);
			sleep(8000);
			setMotorSpeed(motorB, 0);
	}
	_handle_status = 0;
}

void forward(float x){

		int pid , error ,last_error , sum_error, left , right = 0;
		left = SensorValue[S1];
		right = SensorValue[S4];
		left = left > 40 ? 40:left;
		left = left < 5 ? 5:left;
		right = right > 40 ? 40:right;
		right = right < 5 ? 5:right;
		last_error = error;
		//`if(left == 5 && right == 5) beep(1);
		error = left - right;
		sum_error += error;
		pid = error*(x) + (error-last_error)*3;
		setMotorSpeed(motorA, 40+pid);
		setMotorSpeed(motorD, 40+pid*(-1));

}

void backward(float y){
	for(int j = 0 ; j < 10000 ; j++){
		setMotorSpeed(motorA, -50);
		setMotorSpeed(motorD, -50);
	}
}

void two_turn_left(){

	for(int i = 0 ; i < 20000 ; i++){
		setMotorSpeed(motorA,-30);
		setMotorSpeed(motorD,30);
	}
	while(SensorValue[S4] > 10){
		setMotorSpeed(motorA,-30);
		setMotorSpeed(motorD,30);
	}

	stop_motor();

}

void turn_left(){

	for(int i = 0 ; i < 8500 ; i++){
		setMotorSpeed(motorA,-30);
		setMotorSpeed(motorD,30);
	}
	while(SensorValue[S4] > 10){
		setMotorSpeed(motorA,-30);
		setMotorSpeed(motorD,30);
	}

	stop_motor();

}

void turn_right(){

	for(int i = 0 ; i < 8500 ; i++){
		setMotorSpeed(motorA,30);
		setMotorSpeed(motorD,-30);
	}
	while(SensorValue[S1] > 10){
		setMotorSpeed(motorA,30);
		setMotorSpeed(motorD,-30);
	}
	stop_motor();
}

void beep(int i) {
	for (int j = -1; j < i ; j++) {
		playTone(4000, 10);
		sleep(200);
	}
}
